language: c++

env:
  global:
    - GCC_INSTALL_PATH="${HOME}/gcc-concepts"
    - GCC_BUILD_TREE="${HOME}/gcc-concepts-buildtree"
    - GCC_REPO_URL="https://github.com/gcc-mirror/gcc.git"
    - CONCEPTS_TS_COMMIT="56c12fd4ba064759724236ad896232603b8797ed"
    - GCC_SUFFIX="-concepts"
    - GCC_NAME="gcc${GCC_SUFFIX}"
    - GCC_PATH="${GCC_INSTALL_PATH}/bin/${GCC_NAME}"

cache:
  directories:
    - $GCC_INSTALL_PATH

addons:
  apt:
    packages:
      - libmpfr-dev
      - libgmp3-dev
      - libmpc-dev
      - flex
      - bison

before_install:
  - if [[ ! -f "$GCC_PATH" ]]; then rm -rf $GCC_INSTALL_PATH && rm -rf GCC_BUILD_TREE && BUILD_GCC="Please cache, work."; fi

  - if [[ $BUILD_GCC ]]; then git clone $GCC_REPO_URL $GCC_BUILD_TREE && cd $GCC_BUILD_TREE; fi
  - if [[ $BUILD_GCC ]]; then git checkout $CONCEPTS_TS_COMMIT; fi
  - if [[ $BUILD_GCC ]]; then mkdir build && cd build; fi
  - if [[ $BUILD_GCC ]]; then ../configure --prefix=$GCC_INSTALL_PATH --disable-multilib --disable-werror --program-suffix=$GCC_SUFFIX --enable-languages=c++ --enable-version-specific-runtime-libs; fi
  - if [[ $BUILD_GCC ]]; then ../../build_gcc.sh; fi

install:
  - if [[ $BUILD_GCC ]]; then mkdir $GCC_INSTALL_PATH -p; fi
  - if [[ $BUILD_GCC ]]; then make install; fi
  - export CXX=$GCC_PATH
  - $CXX --version

script:
  - ./run.sh 

